# -*- coding: utf-8 -*-
"""CreditCardMatplotlib.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-0YlxM6LjFq67_Ud-q2azaC0tXtZ-Evz
"""

import pandas as pd
df = pd.read_csv("Credit_Card_Fraud_10k (1).csv")
print(df)

# Transaction Analysis
# Total Tansaction
import matplotlib.pyplot as plt
total_transaction = df['Transaction_Id'].nunique()
print('Total Transaction:',total_transaction)

plt.figure(figsize =(4,2))
plt.text(0.5,0.5,
         f"Total Transaction\n{total_transaction}",
         fontsize=20,
         ha="center",
         va="center")
plt.axis("off")
plt.show()

# Total Fraud Transaction
fraud = df[df['Is_Fraud']== 1]
total_fraud = fraud['Transaction_Id'].nunique()
print('Total Fraud Transaction:',total_fraud)

plt.figure(figsize =(4,2))
plt.text(0.5,0.5,
         f"Total Fraud Transaction\n{total_fraud}",
         fontsize=20,
         ha="center",
         va="center")
plt.axis("off")
plt.show()

# Fraud Percentage
fraud_percentage = (len(fraud)/(len(df))) * 100
print('Fraud Percentage:',fraud_percentage)

plt.figure(figsize=(4,2))
plt.text(0.5,0.5,
         f"Fraud Percentage\n{fraud_percentage}",
         fontsize=20,
         ha="center",
         va="center")
plt.axis("off")
plt.show()

# Amount Analysis
# Maximum Amount
maximum_amount = df['Transaction_Amount'].max()
print("Maximum Amount:",maximum_amount)

plt.figure(figsize=(4,2))
plt.text(0.5,0.5,
         f"Maximum Amount\n{maximum_amount}",
         fontsize=20,
         ha="center",
         va="center")
plt.axis("off")
plt.show()

# Minimum Amount
minimum_amount = df['Transaction_Amount'].min()
print("Minimum Amount:",minimum_amount)

plt.figure(figsize=(4,2))
plt.text(0.5,0.5,
          f"Minimum Amount\n{minimum_amount}",
          fontsize=20,
          ha="center",
          va="center")
plt.axis("off")
plt.show()

# Average Amount
average_amount = df['Transaction_Amount'].mean()
print("Average Amount:",average_amount)

plt.figure(figsize=(4,2))
plt.text(0.5,0.5,
         f"Average Amount\n{average_amount}",
         fontsize=20,
         ha="center",
         va="center")
plt.axis("off")
plt.show()

# Median Amount
Median_amount = df['Transaction_Amount'].median()
print("Median Amount:",Median_amount)

plt.figure(figsize=(4,2))
plt.text(0.5,0.5,
         f"Median Amount\n{Median_amount}",
         fontsize=20,
         ha="center",
         va="center")
plt.axis("off")
plt.show()

import pandas as pd
def time_category(hour):
  if 5 <= hour < 12:
    return "Morning"
  elif 12 <= hour < 17:
    return "Afternoon"
  elif 17 <= hour < 21:
    return "Evening"
  else:
    return "Night"
df['Time_Category'] = df['Transaction_Hour'].apply(time_category)
print(df)

fraud_hour = df[df['Is_Fraud'] == 1].groupby("Transaction_Hour").size()
plt.figure(figsize=(10,5))
plt.bar(fraud_hour.index, fraud_hour.values,
        color = "Green")
plt.title("Fraud by Hour")
plt.xlabel("Hour")
plt.ylabel("Fraud Transaction")
plt.xticks(range(24))
plt.show()

# Fraud by Time Distribution
fraud_time = df[df['Is_Fraud'] == 1].groupby("Time_Category").size()

plt.figure(figsize=(10,5))

plt.bar(
    fraud_time.index,
    fraud_time.values,
    width=0.4,      # Bar thickness
    color='red'
)

plt.title("Fraud by Time Distribution")
plt.xlabel("Time Category")
plt.ylabel("Fraud Transactions")

plt.show()

peak = fraud_time.idxmax()
count = fraud_time.max()

print("Peak Fraud Time:",peak)
print("Fraud Transaction:", count)

# Fraud Percentage Pie chart

# Percentages
labels = ['Genuine', 'Fraud']
sizes = [98.49, 1.51]

# Pie Chart
plt.figure(figsize=(6,6))
plt.pie(sizes,
        labels=labels,
        autopct='%1.2f%%',
        startangle=90,
        colors=["Green","Red"])

plt.title("Fraud Percentage", y=1.05)
plt.axis('equal')
plt.show()

# Amount VS Fraud
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

df.boxplot(column='Transaction_Amount', by='Is_Fraud')

plt.title("Amount vs Fraud")
plt.suptitle("")   # Remove extra title
plt.xlabel("Is Fraud (0=Genuine, 1=Fraud)")
plt.ylabel("Transaction Amount")

plt.show()

# Fraud VS Genuine Transaction
import matplotlib.pyplot as plt

counts = df['Is_Fraud'].value_counts()

bars = plt.bar(
    ['Genuine', 'Fraud'],
    [counts[0], counts[1]],
    color=['green', 'red'],
    width=0.5
)

for bar in bars:
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 50,
        int(bar.get_height()),
        ha='center'
    )

plt.title("Fraud vs Genuine Transactions")
plt.xlabel("Transaction Type")
plt.ylabel("Count")

plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.hist(df['Transaction_Amount'],
         bins=30,
         density=True,
         color='purple',
         edgecolor='black')

plt.title("Transaction Amount Distribution")
plt.xlabel("Transaction Amount")
plt.ylabel("Density")

plt.show()