# -*- coding: utf-8 -*-
"""IPLKPI.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GHeDnrcqgdHyOS8zzo-2HrR-QQ-roliY
"""

import pandas as pd
df = pd.read_csv("deliveries.csv")
print(df)

import pandas as pd
df = pd.read_csv("matches.csv")
print(df)

import pandas as pd

df = pd.read_csv("matches.csv")
print(df.info())

import pandas as pd

df = pd.read_csv("deliveries.csv")
print(df.info())

import pandas as pd

df = pd.read_csv("deliveries.csv")
print(df.head())

import pandas as pd

df = pd.read_csv("matches.csv")
print(df.head())

import pandas as pd
df = pd.read_csv("matches.csv")
total_matches = df['id'].nunique()
print("Total Matches :", total_matches)

import matplotlib.pyplot as plt

plt.figure(figsize=(4,2))
plt.text(0.5, 0.5,
         f"Total Matches\n{total_matches}",
         fontsize=20,
         ha="center",
         va="center")

plt.axis("off")
plt.show()

import pandas as pd
df = pd.read_csv("deliveries.csv")
print(df)

runs = df.groupby("batter")["batsman_runs"].sum()

highest_run_scorer = runs.idxmax()
highest_runs = runs.max()

print("Highest Run Score:", highest_run_scorer)
print("Total Runs:", highest_runs)

import matplotlib.pyplot as plt

plt.figure(figsize=(5,2.5))
plt.text(
    0.5, 0.5,
    f"Highest Run Scorer\n{highest_run_scorer}\n{highest_runs} Runs",
    fontsize=16,
    ha="center",
    va="center"
)

plt.axis("off")
plt.show()

wickets = df.groupby("bowler")["is_wicket"].sum()

highest_wicket_taker = wickets.idxmax()
highest_wickets = wickets.max()

print("Highest Wicket Taker:", highest_wicket_taker)
print("Total Wickets:", highest_wickets)

import matplotlib.pyplot as plt

plt.figure(figsize=(5,2.5))
plt.text(
    0.5, 0.5,
    f"Highest Wicket Taker\n{highest_wicket_taker}\n{highest_wickets} Wickets",
    fontsize=16,
    ha="center",
    va="center"
)

plt.axis("off")
plt.show()

import pandas as pd
df = pd.read_csv("matches.csv")
print(df)

team_wins = df["winner"].value_counts()

print(team_wins)

top_team = team_wins.idxmax()
total_wins = team_wins.max()

print("Top Winning Team:", top_team)
print("Total Wins:", total_wins)

import matplotlib.pyplot as plt

plt.figure(figsize=(5,2.5))

plt.text(
    0.5, 0.5,
    f"Top Winning Team\n{top_team}\n{total_wins} Wins",
    fontsize=16,
    ha="center",
    va="center"
)

plt.axis("off")
plt.show()

venue_matches = df["venue"].value_counts()

print(venue_matches)

top_venue = venue_matches.idxmax()
total_matches = venue_matches.max()

print("Top Venue:", top_venue)
print("Matches Played:", total_matches)

import matplotlib.pyplot as plt

plt.figure(figsize=(6,3))

plt.text(
    0.5, 0.5,
    f"Top Venue\n{top_venue}\n{total_matches} Matches",
    fontsize=16,
    ha="center",
    va="center"
)

plt.axis("off")
plt.show()

df["toss_match_win"] = df["toss_winner"] == df["winner"]

toss_impact = df["toss_match_win"].value_counts()

print(toss_impact)

toss_win_match_win = (df["toss_match_win"].sum() / len(df)) * 100

print(f"Toss Winner won the Match: {toss_win_match_win:.2f}%")

import matplotlib.pyplot as plt

plt.figure(figsize=(5,3))

plt.text(
    0.5, 0.5,
    f"Toss Impact\n{toss_win_match_win:.2f}%",
    fontsize=18,
    ha="center",
    va="center"
)

plt.axis("off")
plt.show()

import pandas as pd
matches = pd.read_csv("matches.csv")
deliveries = pd.read_csv("deliveries.csv")

matches.isnull().sum()

# Calculate Total Missing Values
total_missing = matches.isnull().sum().sum()

print("Total Missing Values:", total_missing)

import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(3,2))
ax.axis('off')

ax.text(0.5, 0.65,
        str(total_missing),
        fontsize=28,
        fontweight='bold',
        ha='center')

ax.text(0.5, 0.30,
        "Total Missing Values",
        fontsize=12,
        ha='center')

plt.show()

import pandas as pd

matches = pd.read_csv("matches.csv")
deliveries = pd.read_csv("deliveries.csv")

deliveries.isnull().sum()

# Calculate Total Missing Values
total_missing_deliveries = deliveries.isnull().sum().sum()

print("Total Missing Values:", total_missing_deliveries)

import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(3,2))
ax.axis('off')

ax.text(0.5, 0.65,
        str(total_missing_deliveries),
        fontsize=28,
        fontweight='bold',
        ha='center')

ax.text(0.5, 0.30,
        "Total Missing Values",
        fontsize=12,
        ha='center')

plt.show()

print(matches.shape)
print(deliveries.shape)

print(matches.info())
print(deliveries.info())

matches.duplicated().sum()

duplicate_matches = matches.duplicated().sum()

print("Total Duplicate Records:", duplicate_matches)

import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(3.5,2.2))
ax.axis('off')

ax.text(0.5, 0.65,
        f"{duplicate_matches}",
        fontsize=28,
        fontweight='bold',
        ha='center')

ax.text(0.5, 0.30,
        "Duplicate Records\n(Matches)",
        fontsize=11,
        ha='center')

plt.show()

top_10_runs = (
    deliveries.groupby('batter')['batsman_runs']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print(top_10_runs)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))

top_10_runs.plot(kind='bar')

plt.title("Top 10 Run Scorers in IPL")
plt.xlabel("Batter")
plt.ylabel("Total Runs")
plt.xticks(rotation=45)

plt.show()

# Exclude non-bowler dismissals
bowler_wickets = deliveries[
    ~deliveries['dismissal_kind'].isin(['run out', 'retired hurt', 'obstructing the field'])
]

top_10_wickets = (
    bowler_wickets.groupby('bowler')['is_wicket']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print(top_10_wickets)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))

top_10_wickets.plot(kind='bar')

plt.title("Top 10 Wicket Takers in IPL")
plt.xlabel("Bowler")
plt.ylabel("Total Wickets")
plt.xticks(rotation=45)

plt.show()

orange_cap_data = deliveries.merge(
    matches[['id', 'season']],
    left_on='match_id',
    right_on='id'
)

orange_cap = (
    orange_cap_data
    .groupby(['season', 'batter'])['batsman_runs']
    .sum()
    .reset_index()
)

orange_cap = orange_cap.loc[
    orange_cap.groupby('season')['batsman_runs'].idxmax()
]

print(orange_cap)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))

plt.bar(orange_cap['season'].astype(str),
        orange_cap['batsman_runs'])

plt.title("Season-wise Orange Cap Winners")
plt.xlabel("Season")
plt.ylabel("Runs")
plt.xticks(rotation=45)

plt.show()

purple_cap_data = deliveries.merge(
    matches[['id', 'season']],
    left_on='match_id',
    right_on='id'
)

bowler_wickets = purple_cap_data[
    ~purple_cap_data['dismissal_kind'].isin(
        ['run out', 'retired hurt', 'obstructing the field']
    )
]

purple_cap = (
    bowler_wickets
    .groupby(['season', 'bowler'])['is_wicket']
    .sum()
    .reset_index()
)

purple_cap = purple_cap.loc[
    purple_cap.groupby('season')['is_wicket'].idxmax()
]

print(purple_cap)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))

plt.bar(
    purple_cap['season'].astype(str),
    purple_cap['is_wicket']
)

plt.title("Season-wise Purple Cap Winners")
plt.xlabel("Season")
plt.ylabel("Wickets")
plt.xticks(rotation=45)

plt.show()

venue_matches = matches['venue'].value_counts()

print(venue_matches)

top_10_venues = matches['venue'].value_counts().head(10)

print(top_10_venues)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))

top_10_venues.plot(kind='bar')

plt.title("Top 10 Venues by Number of Matches")
plt.xlabel("Venue")
plt.ylabel("Number of Matches")
plt.xticks(rotation=45)

plt.show()

team_wins = matches['winner'].value_counts()
print(team_wins)

import pandas as pd

team_matches = pd.concat([matches['team1'], matches['team2']]).value_counts()
print(team_matches)

winning_percentage = ((team_wins / team_matches) * 100).round(2)
winning_percentage = winning_percentage.sort_values(ascending=False)

print(winning_percentage)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))

winning_percentage.plot(kind='bar')

plt.title("Team-wise Winning Percentage")
plt.xlabel("Teams")
plt.ylabel("Winning Percentage (%)")
plt.xticks(rotation=45)

plt.show()

matches['toss_match_win'] = matches['toss_winner'] == matches['winner']

toss_match_result = matches['toss_match_win'].value_counts()

print(toss_match_result)

toss_match_percentage = (
    matches['toss_match_win']
    .value_counts(normalize=True) * 100
).round(2)

print(toss_match_percentage)

import matplotlib.pyplot as plt

plt.figure(figsize=(6,6))

toss_match_percentage.plot(
    kind='pie',
    autopct='%1.1f%%',
    labels=['Won Match', 'Lost Match'],
    startangle=90
)

plt.title("Toss Winner vs Match Winner")
plt.ylabel("")
plt.show()

season_final = matches.groupby('season').last().reset_index()

season_final[['season', 'winner']]

season_champion = season_final[['season', 'winner']]

print(season_champion)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))

plt.bar(
    season_champion['season'].astype(str),
    season_champion['winner'].astype(str)
)

plt.title("Season-wise IPL Champions")
plt.xlabel("Season")
plt.ylabel("Champion Team")
plt.xticks(rotation=45)

plt.show()

player_of_match = matches['player_of_match'].value_counts()

print(player_of_match)

top_10_pom = matches['player_of_match'].value_counts().head(10)

print(top_10_pom)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))

top_10_pom.plot(kind='bar')

plt.title("Top 10 Player of the Match Award Winners")
plt.xlabel("Player")
plt.ylabel("Number of Awards")
plt.xticks(rotation=45)

plt.show()

most_pom_player = matches['player_of_match'].value_counts().idxmax()
most_pom_awards = matches['player_of_match'].value_counts().max()

print("Player:", most_pom_player)
print("Awards:", most_pom_awards)